a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
addition = str(a+b) 
subtraction = str(a-b) 
multiplication = str(a*b) 
division = str(a/b) 
print("Sum: " + addition)
print("Difference: " + subtraction)
print("Product: " + multiplication)
print("Quotient: " + division)